### PR TITLE
Migration#18/creation of models

### LINKED ISSUE #18: Create migrations and models
Creation of the database models and at the same time the creation of migrations from console instructions.

### PR DESCRIPTION
**Pull request by jairolan**
# Description
What did you implemented/Why did you implemented this:
 - I have added the models to be used by the database.
 - These models were implemented to start relating the information fields between models.
 - I have added an initializer for the irregular word employee attendance to avoid future errors with active record. 
 - I have added the database migrations, so that they can be compiled and the schema file can be created.

### CODE REVIEW

**Review by oramasangel — DISMISSED** [review]
It looks good to start the backend for the CRUD system

**Review by YilKanda — DISMISSED** [review]
LGTM!

**Review by xFerchoVJ — DISMISSED** [review]
LGTM! :)

**Review by juliocabrera820 — COMMENTED** [review]
@jairolan You must remove the test folder created by a rails generator,because we'll use RSpec

**Review by juliocabrera820 — APPROVED** [review]
*LGTM!*

**Comment by brayandiazc** [comment]
ok, good job

**Review by xFerchoVJ — APPROVED** [review]

**Pull request merged**
