### PR TITLE
Feature#20/unit tests

### LINKED ISSUE #20: Make unit test
# REQUIREMENTS
- Write unit tests for the models.
- Test references between models.
- Test Company model validations.

# DESIGN
image

image

# Acceptance Criteria
- [x] test validations of company model
- [x] test relation between models

### PR DESCRIPTION
**Pull request by jairolan**
# Description
What did you implemented/Why did you implemented this:
 - I refactored the relationships in each of the models.
 - I wrote the unit tests for the relationships between models.
 - Thanks to the unit tests it was possible to refactor the relationship lines in the models.
 - I added in the test for the validations of the Company model.

### CODE REVIEW

**Review by MartinSGL — DISMISSED** [review]

**Review by juliocabrera820 — DISMISSED** [review]
👍🏼

**Comment by brayandiazc** [comment]
Perfect

**Review by oramasangel — DISMISSED** [review]
good relationship on models

**Review by oramasangel — APPROVED** [review]
nice relationship on models

**Review by JoseRicardoJimenez — APPROVED** [review]

**Pull request merged**
