### PR TITLE
Enhancement#69/deployment

### LINKED ISSUE #69: deploy to heroku
# REQUIREMENTS
- Set up production seeder

# Acceptance Criteria
List all required acceptance criteria
- [x] Run on production

### PR DESCRIPTION
**Pull request by juliocabrera820**
# Description

- I just set up a seeder to be executed in production

### CODE REVIEW

**Review by jairolan — DISMISSED** [review]

**Review by YilKanda — DISMISSED** [review]
LGTM!

**Review by JoseRicardoJimenez — DISMISSED** [review]
OK!

**Review by jairolan — DISMISSED** [review]

**Review by oramasangel — DISMISSED** [review]
GOOD

**Review by JoseRicardoJimenez — APPROVED** [review]
(Y)

**Review by jairolan — APPROVED** [review]

**Review by oramasangel — APPROVED** [review]
GJ

**Pull request merged**
